### ISSUE TITLE
OpenSprinkler don't save anymore http hexadecimal characters in cmd, can't works anymore with Tasmota

### ISSUE THREAD

**Issue by Tikilou** [OpenSprinkler/OpenSprinkler-Firmware#294] opened 2024-07-29 13:06 UTC
Hi! First of all, many thanks for all the work you've done on the opensprinkler.

With my previous opensprinkler setup under OsPI with electrical outlets connected under tasmota firmware, I was using http commands to turn them on and off. (To pump water from the well)
This release concerned firmware 2.2.0, running on Raspberry pi 4 and RaspiOS Bullseye.
Following an update to the OpenSprinkler firmware, I can no longer switch my connected sockets on and off.
The reason seems quite simple, visually at least I've noticed that when I indicate an http station type and register the start (cm?cmnd=Power%20On) or stop (cm?cmnd=Power%20Off of the socket) command, on last year's version 2.2.0, the command was registered as is.
Following the update, commands are now recorded as follows:

cm?cmnd=Power On
cm?cmnd=Power Off

As you can see, OpenSprinkler registers the command with a space without "%20", making it impossible to activate/stop the pump outlets.

To put this in context, I'm using OpenSprinkler (OsPI with Raspberry PI 4) with Home Assistant, Tasmota, Ecowitt, humidity and rain sensors, OpenWRT routers and Proxmox servers in a nursery I'm setting up.
I've written a big tutorial of my setup to popularize the use of OpenSprinkler and Open Source bricks in France for private and professional irrigation and water saving. :-)
https://pepinature.org/fr/gestion_de_l_eau/programmation_avancee_et_automatisation_de_l_irrigation

![Capture d’écran du 2024-07-29 15-04-37](https://github.com/user-attachments/assets/7252097b-54e0-4eea-a992-8ebcb08a9446)
![Capture d’écran du 2024-07-29 15-04-49](https://github.com/user-attachments/assets/04ba13a1-9b96-497a-8b9a-1568b89f79a8)

**Comment by rayshobby** [comment] 2024-07-29 13:46
The issue is that %20 is being URI decoded to a space character. I think you can solve this problem by URI encoding %, which is %25. So try:
cm?cmnd=Power%2520On
and see if it works. The only problem is that you have to do this encoding every time you save the HTTP zone settings, otherwise it gets translated to space again.

**Comment by Tikilou** [comment] 2024-07-29 15:24
> The issue is that %20 is being URI decoded to a space character. I think you can solve this problem by URI encoding %, which is %25. So try: cm?cmnd=Power%2520On and see if it works. The only problem is that you have to do this encoding every time you save the HTTP zone settings, otherwise it gets translated to space again.

Thanks ! Unfortunatly it didn't works, electrical outlets with tasmota don't turn on or off with your trick.

I've compiled the fork by [opensprinklershop(.de) v2.3.1](https://github.com/opensprinklershop/OpenSprinkler-Firmware) and this bug is not in this release, it's works fine now, %20 is saved. :-)

**Comment by rayshobby** [comment] 2024-07-29 15:56
It looks like the main difference is Stefan's firmware doesn't do urlDecode:
https://github.com/opensprinklershop/OpenSprinkler-Firmware/blob/master/opensprinkler_server.cpp#L679
whereas our firmware does:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/opensprinkler_server.cpp#L611

It's pretty easy to change it, but I want to be careful with other implications of this change, i.e. it may work for you but not work for other users due to their commands having encoded characters. Honestly I don't know how the command parameter itself has a space character in it, this is quite unusual I feel. Why not use an underscore like Power_On instead of Power%20On.

**Comment by rayshobby** [comment] 2024-07-30 15:38
OK, I am closing this issue for now and will respond in the new issue.

**Closed by rayshobby** 2024-07-30 15:38 UTC
