### ISSUE TITLE
Flow sensor phantom counts

### ISSUE THREAD

**Issue by n3xus1** [OpenSprinkler/OpenSprinkler-Firmware#201] opened 2022-02-27 01:41 UTC
opensprinkler Pi with raspberry pi 2B version 1.1 

using default install of bullseye causes the flow sensor to count with not input connected
issue is not present on default install of legacy buster with same configuration

**Comment by mattriney** [comment] 2022-04-01 19:21
I have this issue as well. There also seems to be an issue with the rain sensor not changing properly when triggered/cleared.

**Comment by mattriney** [comment] 2022-04-01 21:09
Just confirmed rolling back to buster does not show the same phantom flow sensor counts.

**Comment by mattriney** [comment] 2022-04-02 03:01
The flow sensor reading goes erratic after being triggered for the first time and never goes back to baseline as seen in this graph
![Screenshot 2022-04-01 215921](https://user-images.githubusercontent.com/61891660/161363314-c96e131b-056d-44ea-bc17-3335645f79c7.jpg)
.

**Comment by rayshobby** [comment] 2022-11-03 12:54
The issue with bullseye is that it no longer supports wiringPi, which is needed (specifically, the 'gpio' command that comes with wiringPi) to enable the internal pull-up resistor on the sensor pins. This will be resolved in the next firmware by changing to use 'raspi-gpio' command instead.

**Closed by rayshobby** 2022-11-03 12:54 UTC
