### ISSUE TITLE
disabling system does not prevent programs from running, or ...

### ISSUE THREAD

**Issue by docsparks** [OpenSprinkler/OpenSprinkler-Firmware#178] opened 2021-05-21 07:27 UTC
rpi based, 2.1.9(4), using hamburger menu in upper left side of screen

choosing the 'Disable operation' option does not stop programs from running

also also allows me to manually run a station (say my homeassistant is programmed to manually run a station via http request) and the disable operation feature is enabled, opensprinkler runs as expected, with no care the system is technically 'disabled'

preferably, while cleaning water tanks, i would rather not have to manually disable the programs , and choosing disable operation is usually my goto thought.

**Comment by rayshobby** [comment] 2021-05-21 18:13
First of all, please use the latest firmware 2.1.9(7) as older firmwares may have bugs that have already been fixed in the latest version. Second, system disable will turn off all zones at run-time, so even if a program has been scheduled, the zones will be turned off. This is evident in this line of code:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/main.cpp#L1171
Next, manually started runs are NOT affected by system disable, because it is understood that if you manually start a zone, you intend to overwrite the system disable, otherwise there is no reason to start a zone while the system is disabled. This is expected behavior and is evident in this line:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/main.cpp#L1167
a manually started program has program ID 255. This behavior was requested by other users in the past as they want to do ad-hoc watering even when the controller is disabled otherwise -- which means automatic program runs will be stopped.

**Closed** 2021-05-25 13:22 UTC
