### ISSUE TITLE
Empty Response ("wterr": -4, received empty return) answer requesting the weather service

### ISSUE THREAD

**Issue by FranzStein** [OpenSprinkler/OpenSprinkler-Firmware#197] opened 2022-01-24 12:59 UTC
If using the default OpenSprinler Weather Service: http://weather.opensprinkler.com the OpenSprinkler doesn’t always receive the requested Weather Service Details from the OpenSprinkler Weather Service. The answer listed in the OpenSprinkler App is “Empty Response” and the Weather Service is marked as “Offline”. The OpenSprinkler App uses the Get Controller Variables /jc?pw=xxx command to receive the OpenSprinkler information. Starting this command in a web browser results in:

{"devt":1642960724,"nbrd":1,"en":1,"sn1":0,"sn2":0,"rd":0,"rdst":0,"sunrise":480,"sunset":1017,"eip":1339801819,"lwc":1642957305,"lswc":1642942897,"lupt":1642903274,"lrbtc":99,"lrun":[0,0,0,0],"RSSI":-42,"mac":"60:01:94:70:87:60","loc":"49.47432,10.94365","jsp":"https://ui.opensprinkler.com/js","wsp":"weather.opensprinkler.com","wto":{"h":100,"t":100,"r":100,"bh":65,"bt":69.8,"br":0,"pws":"IFRTH65","key":""},"ifkey":"bu9J7THcINuUAoUYzayc77","mqtt":{},"wtdata":{"wp":"DS","h":93.63,"p":0.13,"t":35.8,"raining":1},"wterr":-4,"curr":0,"sbits":[0,0],"ps":[[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]}

The error code of the last response from the weather server is “wterr”: -4. However, the “wtdata”: {} is populated correctly!

I'm not sure what's the issue here. I first thought it's a WiFi router or WiFi repeater issue? Resetting the OpenSprinkler and also the WiFi router to its factory installation and starting it again does not solve the problem, which is not easily to trigger. 

My OpenSprinkler used is a v3.0 hardware model. The App reports: App Version: 2.2.4, Firmware: 2.1.9(9), Hardware Version:3.1-DC. This means everything is updated to the newest releases!

**Comment by rayshobby** [comment] 2022-11-03 12:56
Does this issue still persists? It possibly has to do with the http response header being too long (due to additional headers that cloudflare inserts). The issue is described here:
https://opensprinkler.com/forums/topic/opensprinkler-firmware-2-1-911-is-available-weather-query-bug-fix/
since then we have also configured cloudflare to remove those additional headers, so if your issue is caused by the extra long header, it should be resolved by now.

**Closed** 2022-12-13 02:30 UTC
